name: Upload 4C Build
description: Uploads the 4C build in a tarball as artifact
inputs:
  build-directory:
    description: Path to the build directory
    required: true
  retention-days:
    description: Number of days to retain the artifact
    required: false
    default: "1"
runs:
  using: composite
  steps:
    - name: Install pigz
      shell: bash
      run: apt-get update && apt-get install -y pigz
    - name: Package build directory
      shell: bash
      run: tar -c --use-compress-program=pigz -f $GITHUB_WORKSPACE/4C_build.tar.gz $GITHUB_WORKSPACE/build
    - name: Upload build folder
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.job }}-4C-build
        path: |
          ${{ github.workspace }}/4C_build.tar.gz
        retention-days: ${{ inputs.retention-days }}
