name: Configure 4C
description: Configure the build directory of 4C with a specified preset
inputs:
  cmake-preset:
    description: Name of the preset
    required: true
    default: docker
  build-directory:
    description: Path to the build directory
    required: true
  additional-cmake-flags:
    description: Additional flags passed to cmake
    required: false
    default: ""
runs:
  using: composite
  steps:
    - name: Fix git
      shell: bash
      run: git config --global --add safe.directory $GITHUB_WORKSPACE
    - name: Prepare directory
      run: mkdir -p $BUILD_DIRECTORY
      shell: bash
      env:
        BUILD_DIRECTORY: ${{ inputs.build-directory }}
    - name: Configure 4C with preset ${{ inputs.cmake-preset }}
      run: |
        cd $GITHUB_WORKSPACE
        ./utilities/set_up_dev_env.sh
        cd $BUILD_DIRECTORY
        # use xargs as $ADDITIONAL_CMAKE_FLAGS can contain multiple flags
        echo $GITHUB_WORKSPACE --fresh --preset=$CMAKE_PRESET $ADDITIONAL_CMAKE_FLAGS | xargs cmake
        cd $GITHUB_WORKSPACE
      shell: bash
      env:
        BUILD_DIRECTORY: ${{ inputs.build-directory }}
        CMAKE_PRESET: ${{ inputs.cmake-preset }}
        ADDITIONAL_CMAKE_FLAGS: ${{ inputs.additional-cmake-flags }}
