name: deploy

on:
  workflow_run:
    workflows: [documentation]
    types: [completed]
    branches: [main]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-24.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.repository == '4C-multiphysics/4C'
      }}
    steps:
      - uses: dawidd6/action-download-artifact@v6
        with:
          workflow: documentation.yml
          name: doxygen
          path: ${{ github.workspace }}/doxygen
      - uses: dawidd6/action-download-artifact@v6
        with:
          workflow: documentation.yml
          name: readthedocs
          path: ${{ github.workspace }}/readthedocs
      - uses: actions/upload-pages-artifact@v3
        id: deployment
        with:
          path: ${{ github.workspace }}
          retention-days: 1
      - uses: actions/deploy-pages@v4

