name: Docker with deal.II

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  PROJECT_NAMESPACE: 4c-multiphysics
  IMAGE_SUFFIX: dependencies

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dummy:
    steps:
      - shell: bash
        run: echo "Dummy job"
    runs-on: ubuntu-latest
