name: documentation

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

env:
  FOUR_C_DOCKER_DEPENDENCIES_HASH: 40d8b295

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  doxygen:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/4c-multiphysics/4c-dependencies:40d8b295
      options: --user root --env OMPI_ALLOW_RUN_AS_ROOT=1 --env OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Check docker hash
        uses: ./.github/actions/compute-and-check-dependencies-hash
        with:
          docker_image_hash: $FOUR_C_DOCKER_DEPENDENCIES_HASH
      - uses: ./.github/actions/configure_4C
        with:
          cmake-preset: docker
          build-directory: ${{ github.workspace }}/build
      - uses: ./.github/actions/build_4C
        with:
          build-targets: doxygen
          build-directory: ${{ github.workspace }}/build
      - name: Upload doxygen
        uses: actions/upload-artifact@v4
        with:
          name: doxygen
          path: ${{ github.workspace }}/build/doc/doxygen/html/
          retention-days: 1

  readthedocs:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/4c-multiphysics/4c-dependencies:40d8b295
      options: --user root --env OMPI_ALLOW_RUN_AS_ROOT=1 --env OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Check docker hash
        uses: ./.github/actions/compute-and-check-dependencies-hash
        with:
          docker_image_hash: $FOUR_C_DOCKER_DEPENDENCIES_HASH
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}-${{ env.CMAKE_PRESET }}
      - uses: ./.github/actions/configure_4C
        with:
          cmake-preset: docker
          build-directory: ${{ github.workspace }}/build
          additional-cmake-flags: -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
      - uses: ./.github/actions/build_4C
        with:
          build-targets: readthedocs
          build-directory: ${{ github.workspace }}/build
      - name: Upload readthedocs
        uses: actions/upload-artifact@v4
        with:
          name: readthedocs
          path: ${{ github.workspace }}/build/doc/readthedocs/html/
          retention-days: 1
